#!/bin/sh
set -eo pipefail

if [[ -z "$1" ]]; then
  echo "Usage: $0 <pool_name>"
  exit 1
fi

pool_name="$1"
fs_name="${pool_name}/minio"

echo ==================== OpenZFS 创建文件系统 ${fs_name} ====================

if ! zpool list "$pool_name" &>/dev/null; then
  echo "Error: zfs pool '$pool_name' not found!"
  exit 1
fi

# if [[ -d "/${fs_name}" ]]; then
#   echo "Directory exists: /${fs_name}"
#   exit 1
# fi

zfs create ${fs_name}
zfs set relatime=off compression=zstd logbias=throughput recordsize=128K sync=disabled ${fs_name}

zfs_opts='name,used,available,referenced,mountpoint,compression,compressratio,recordsize,logbias,sync,primarycache,readonly,mounted,creation,'
zfs list -o "${zfs_opts}"
zfs-set-quota ${fs_name} 50  # 50% of the pool

