#!/bin/sh
set -eo pipefail
# https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/index.html
# https://www.rockylinux.cn/notes/strong-diy-nas-xi-lie-03-an-zhuang-zfs-wen-jian-xi-tong.html
# https://201.ustclug.org/ops/storage/zfs/#tuning
# https://bun.uptrace.dev/postgres/tuning-zfs-aws-ebs.html

echo ==================== OpenZFS 创建存储池 /${pool_name} ====================

pool_name="$1"
if [[ -z "${pool_name}" ]]; then
  echo "Usage: $0 <pool_name> <disk>"
  echo "Example: $0 data /dev/nvme0n2"
fi

disk="$2"
if [[ -z "${disk}" ]]; then
  echo "Usage: $0 <by-id>|<by-path>|<by-uuid>"
  echo "Example: $0 pci-0000:0b:00.0-nvme-2 | nvme-eui.b1b...d7 | /dev/nvme0n2 "
  tree /dev/disk/
  lsblk
  exit 1
fi

if [[ -d "/${pool_name}" ]]; then
  echo "Directory exists: /${pool_name}"
  exit 1
fi

zpool create -o ashift=12 -o autotrim=off ${pool_name} -m /${pool_name} "${disk}"
zpool set autoreplace=on ${pool_name}
zfs set dedup=off atime=on relatime=on xattr=sa compression=zstd logbias=latency recordsize=128K ${pool_name}
systemctl enable zfs-scrub-weekly@${pool_name}.timer --now
# systemctl enable zfs-trim-weekly@${pool_name}.timer --now

zpool status -t ${pool_name}
zpool list
# zfs list
# zfs get sync
# zfs get compression

zfs_opts='name,used,available,referenced,mountpoint,compression,recordsize,logbias,sync,primarycache,readonly,mounted,exec,creation,compressratio,'
zfs list -o "${zfs_opts}"

# zfs-set-refquota ${pool_name} 70
zfs-set-quota ${pool_name} 70
arcstat
# cat /proc/spl/kstat/zfs/arcstats

# sudo zfs snapshot data/log@$(date_ft)
# zfs list -t snapshot

