#!/bin/sh
set -eo pipefail

pool_name="postgres"

echo ==================== OpenZFS 创建存储池 /${pool_name} ====================

disk="${1}"

if [[ -z "${disk}" ]]; then
  echo "Usage: $0 <by-id>|<by-path>|<by-uuid>"
  echo "Example: $0 pci-0000:0b:00.0-nvme-2 | nvme-eui.b1b...d7 | /dev/nvme0n2 "
  tree /dev/disk/
  lsblk
  exit 1
fi

if [[ -d "/${pool_name}" ]]; then
  echo "Directory exists: /${pool_name}"
  exit 1
fi

zpool create -o ashift=12 -o autotrim=on ${pool_name} -m /${pool_name} "${disk}"
zfs set dedup=off atime=off relatime=off xattr=sa compression=zstd-fast logbias=latency recordsize=32K ${pool_name}
systemctl enable zfs-scrub-weekly@${pool_name}.timer --now
# systemctl enable zfs-trim-weekly@${pool_name}.timer --now

zpool list
zfs_opts='name,used,available,referenced,mountpoint,compression,compressratio,recordsize,logbias,sync,primarycache,readonly,mounted,creation,'
zfs list -o "${zfs_opts}"

zfs-set-refquota ${pool_name} 90
arcstat
# cat /proc/spl/kstat/zfs/arcstats

